### ISSUE TITLE
docs: Update `README.md`

### ISSUE THREAD

**Issue by aayushchugh** [aayushchugh/maya#23]
### Project

Core

### Description

Add following things in the `REAMDE`

1. Add section to invite users to official discord server
2. Basic details about monorepos and how to use yarn workspaces

### Anything else?

Discord invite link: https://discord.com/invite/A2GdYbwAnw
Yarn workspaces: https://yarnpkg.com/features/workspaces

**Comment by Vanshhemu** [comment]
:D
